print(True or False)
print(False or True)
print(True or False)
print(True or False)
print(True or False)
print(True or False)
print(True or False)
print(True or False)
print(True or False)
print(True or False)


print(True and False)
print(True and False)
print(True and False)
print(True and False)
print(True and False)
print(True and False)
print(True and False)
print(True and False)
print(True and False)
print(True and False)